### ISSUE TITLE
Error while trying to launch gtkcord4

### ISSUE THREAD

**Issue by Scemworks** [diamondburned/gtkcord4#14]
```
2022/04/28 16:32:14 failed to read user.css: open /home/mariowala/.config/gtkcord4/user.css: no such file or directory
2022/04/28 16:32:14 note: account not found from driver: key not found
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2a0 pc=0x7f5aad509d8b]

runtime stack:
runtime.throw({0x555d8ece2969?, 0x0?})
	runtime/panic.go:992 +0x71
runtime.sigpanic()
	runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x555d8ec178a0, 0xc00014d908)
	runtime/cgocall.go:157 +0x5c fp=0xc00014d8e0 sp=0xc00014d8a8 pc=0x555d8d9e5bdc
github.com/diamondburned/gotk4/pkg/gtk/v4._Cfunc_gtk_widget_show(0x7f5ac82702b0)
	_cgo_gotypes.go:53255 +0x45 fp=0xc00014d908 sp=0xc00014d8e0 pc=0x555d8dec0165
github.com/diamondburned/gotk4/pkg/gtk/v4.(*Widget).Show.func1(0xc0004f6180?)
	github.com/diamondburned/gotk4/pkg@v0.0.0-20220417091308-856167c02355/gtk/v4/gtkwidget.go:6031 +0x3a fp=0xc00014d940 sp=0xc00014d908 pc=0x555d8e037f3a
github.com/diamondburned/gotk4/pkg/gtk/v4.(*Widget).Show(0xc00035e070)
	github.com/diamondburned/gotk4/pkg@v0.0.0-20220417091308-856167c02355/gtk/v4/gtkwidget.go:6031 +0x45 fp=0xc00014d958 sp=0xc00014d940 pc=0x555d8e037ec5
main.(*manager).activate(0xc0000d6618, {0x555d8f357d48?, 0xc000114e00})
	github.com/diamondburned/gtkcord4/main.go:59 +0x9e fp=0xc00014d980 sp=0xc00014d958 pc=0x555d8ebd277e
main.main.func1()
	github.com/diamondburned/gtkcord4/main.go:31 +0x2e fp=0xc00014d9a8 sp=0xc00014d980 pc=0x555d8ebd262e
github.com/diamondburned/gotk4/pkg/gio/v2._gotk4_gio2_Application_ConnectActivate(0x555d8d9e6206?, 0xc0000021a0?)
	github.com/diamondburned/gotk4/pkg@v0.0.0-20220417091308-856167c02355/gio/v2/gapplication.go:592 +0x74 fp=0xc00014d9f0 sp=0xc00014d9a8 pc=0x555d8db95a74
_cgoexp_60a35a354f58__gotk4_gio2_Application_ConnectActivate(0x7f5ae7509190?)
	_cgo_gotypes.go:29276 +0x25 fp=0xc00014da10 sp=0xc00014d9f0 pc=0x555d8dc89d85
runtime.cgocallbackg1(0x555d8dc89d60, 0xc00014dbc8?, 0x0)
	runtime/cgocall.go:314 +0x2ca fp=0xc00014dae0 sp=0xc00014da10 pc=0x555d8d9e610a
runtime.cgocallbackg(0xc0000021a0?, 0x300000002?, 0xc0000021a0?)
	runtime/cgocall.go:233 +0x109 fp=0xc00014db70 sp=0xc00014dae0 pc=0x555d8d9e5d89
runtime.cgocallbackg(0x555d8dc89d60, 0x7f5ae75096d0, 0x0)
	<autogenerated>:1 +0x31 fp=0xc00014db98 sp=0xc00014db70 pc=0x555d8da49331
runtime.cgocallback(0x555d8d9e5c05, 0x555d8ec3b010, 0xc00014dc28)
	runtime/asm_amd64.s:971 +0xb3 fp=0xc00014dbc0 sp=0xc00014db98 pc=0x555d8da46d73
runtime.systemstack_switch()
	runtime/asm_amd64.s:436 fp=0xc00014dbc8 sp=0xc00014dbc0 pc=0x555d8da44d20
runtime.cgocall(0x555d8ec3b010, 0xc00014dc28)
	runtime/cgocall.go:167 +0x85 fp=0xc00014dc00 sp=0xc00014dbc8 pc=0x555d8d9e5c05
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x555d90c1a290, 0x1, 0x7f5ac8002440)
	_cgo_gotypes.go:5616 +0x50 fp=0xc00014dc28 sp=0xc00014dc00 pc=0x555d8db40f90
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0xc0000db0f0?, 0x8?, 0x7f5ac8002440?)
	github.com/diamondburned/gotk4/pkg@v0.0.0-20220417091308-856167c02355/gio/v2/gapplication.go:1619 +0x71 fp=0xc00014dc70 sp=0xc00014dc28 pc=0x555d8db992f1
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc0000d6630, {0xc0001921f0?, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.0.0-20220417091308-856167c02355/gio/v2/gapplication.go:1619 +0x1d8 fp=0xc00014dd30 sp=0xc00014dc70 pc=0x555d8db991d8
github.com/diamondburned/gotkit/app.(*Application).Run(0xc00011e780, {0x555d8f357d80, 0xc00019e000}, {0xc0001921f0, 0x1, 0x1})
	github.com/diamondburned/gotkit@v0.0.0-20220418090814-3d8ad765902d/app/app.go:237 +0x189 fp=0xc00014dd90 sp=0xc00014dd30 pc=0x555d8e2681c9
github.com/diamondburned/gotkit/app.(*Application).RunMain(0x555d8f35a6e0?, {0x555d8f357d80?, 0xc00019e000?})
	github.com/diamondburned/gotkit@v0.0.0-20220418090814-3d8ad765902d/app/app.go:242 +0x38 fp=0xc00014ddd0 sp=0xc00014dd90 pc=0x555d8e268358
main.main()
	github.com/diamondburned/gtkcord4/main.go:32 +0x1fd fp=0xc00014df80 sp=0xc00014ddd0 pc=0x555d8ebd25dd
runtime.main()
	runtime/proc.go:250 +0x213 fp=0xc00014dfe0 sp=0xc00014df80 pc=0x555d8da18eb3
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc00014dfe8 sp=0xc00014dfe0 pc=0x555d8da46fc1

goroutine 7 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

goroutine 5 [chan receive]:
github.com/diamondburned/gotkit/gtkutil/aggressivegc.init.0.func1()
	github.com/diamondburned/gotkit@v0.0.0-20220418090814-3d8ad765902d/gtkutil/aggressivegc/aggressivegc.go:17 +0x65
created by github.com/diamondburned/gotkit/gtkutil/aggressivegc.init.0
	github.com/diamondburned/gotkit@v0.0.0-20220418090814-3d8ad765902d/gtkutil/aggressivegc/aggressivegc.go:16 +0x25

goroutine 8 [select]:
os/signal.NotifyContext.func1()
	os/signal/signal.go:288 +0x70
created by os/signal.NotifyContext
	os/signal/signal.go:287 +0x165

goroutine 9 [chan receive]:
github.com/diamondburned/gotkit/app.(*Application).Run.func1()
	github.com/diamondburned/gotkit@v0.0.0-20220418090814-3d8ad765902d/app/app.go:233 +0x36
created by github.com/diamondburned/gotkit/app.(*Application).Run
	github.com/diamondburned/gotkit@v0.0.0-20220418090814-3d8ad765902d/app/app.go:232 +0x165

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7f5ae4c8b7d8, 0x72)
	runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000096380?, 0xc00033cf60?, 0x0)
	internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).ReadMsg(0xc000096380, {0xc00033cf60, 0x10, 0x10}, {0xc00026c620, 0x1000, 0x1000}, 0x4?)
	internal/poll/fd_unix.go:304 +0x31c
net.(*netFD).readMsg(0xc000096380, {0xc00033cf60?, 0xc00015af60?, 0xc00033cf4c?}, {0xc00026c620?, 0xc00033ce66?, 0xc00033ce60?}, 0xc00033ce5c?)
	net/fd_posix.go:78 +0x37
net.(*UnixConn).readMsg(0xc00009a000, {0xc00033cf60?, 0xc00015cb50?, 0x555d8f351908?}, {0xc00026c620?, 0x555d8f359c90?, 0x555d90aaafb8?})
	net/unixsock_posix.go:115 +0x4f
net.(*UnixConn).ReadMsgUnix(0xc00009a000, {0xc00033cf60?, 0xc00012ddb8?, 0x555d8d9ef6e5?}, {0xc00026c620?, 0x555d8da7206b?, 0x555d8f359c90?})
	net/unixsock.go:143 +0x3c
github.com/godbus/dbus/v5.(*oobReader).Read(0xc00026c600, {0xc00033cf60?, 0xc00012dde0?, 0x555d8d9efa47?})
	github.com/godbus/dbus/v5@v5.0.6/transport_unix.go:21 +0x45
io.ReadAtLeast({0x555d8f351ea8, 0xc00026c600}, {0xc00033cf60, 0x10, 0x10}, 0x10)
	io/io.go:331 +0x9a
io.ReadFull(...)
	io/io.go:350
github.com/godbus/dbus/v5.(*unixTransport).ReadMessage(0xc00007e000)
	github.com/godbus/dbus/v5@v5.0.6/transport_unix.go:91 +0x11e
github.com/godbus/dbus/v5.(*Conn).inWorker(0xc00032a000)
	github.com/godbus/dbus/v5@v5.0.6/conn.go:389 +0x48
created by github.com/godbus/dbus/v5.(*Conn).Auth
	github.com/godbus/dbus/v5@v5.0.6/auth.go:118 +0x98d

goroutine 23 [chan receive]:
github.com/godbus/dbus/v5.newConn.func1()
	github.com/godbus/dbus/v5@v5.0.6/conn.go:288 +0x32
created by github.com/godbus/dbus/v5.newConn
	github.com/godbus/dbus/v5@v5.0.6/conn.go:287 +0x176

```

**Comment by diamondburned** [comment]
Huh interesting. Can you `gdb` it with a debug-enabled GTK?

**Comment by Scemworks** [comment]
output of `gdb ./gtkcord4`
```
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./gtkcord4...
(No debugging symbols found in ./gtkcord4)
(gdb)
```

**Comment by diamondburned** [comment]
You have to run the program. See https://www.thegeekstuff.com/2014/01/gdb-backtrace/. Breakpoints not needed.

**Comment by Scemworks** [comment]
Output after running gtkcord4 with gdb
```
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file ./gtkcord4
Reading symbols from ./gtkcord4...
Loading Go Runtime support.
```

**Comment by Scemworks** [comment]
output after running `./gtkcord4 %U`
```
2022/05/03 09:20:49 failed to read user.css: open /home/mariowala/.config/gtkcord4/user.css: no such file or directory
2022/05/03 09:20:49 Critical: GLib-GIO: This application can not open files.
```

**Comment by chrisdebian** [comment]
Hi, @Scemworks. This issue is nearly 3 years old, do you know if the problem still exists in the latest release?
