### ISSUE TITLE
gtkcord4 randomly freezes (traces to present_popup)

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gtkcord4#47]
```
(gdb) bt
#0  0x00007ffff6ff45d9 in poll () from /nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib/libc.so.6
#1  0x00007ffff681f67c in wl_display_dispatch_queue () from /nix/store/44hmz0z4zajjzkf1dxzvnhs12hfg0nka-wayland-1.21.0/lib/libwayland-client.so.0
#2  0x00007ffff7bf84e3 in gdk_wayland_surface_present_popup () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#3  0x00007ffff79d23de in present_popup () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#4  0x00007ffff79d26a8 in surface_transform_changed_cb () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#5  0x00007ffff7abd860 in sync_widget_surface_transform () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#6  0x00007ffff7abd8cc in parent_surface_transform_changed_cb () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#7  0x00007ffff7abd860 in sync_widget_surface_transform () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#8  0x00007ffff7abd8cc in parent_surface_transform_changed_cb () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#9  0x00007ffff7abd860 in sync_widget_surface_transform () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#10 0x00007ffff7abd8cc in parent_surface_transform_changed_cb () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#11 0x00007ffff7abd860 in sync_widget_surface_transform () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#12 0x00007ffff7abd8cc in parent_surface_transform_changed_cb () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#13 0x00007ffff7abd860 in sync_widget_surface_transform () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#14 0x00007ffff7abd8cc in parent_surface_transform_changed_cb () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#15 0x00007ffff7abd860 in sync_widget_surface_transform () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#16 0x00007ffff7abd8cc in parent_surface_transform_changed_cb () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#17 0x00007ffff7abd860 in sync_widget_surface_transform () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#18 0x00007ffff7ac0b91 in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#19 0x00007ffff7ab1b3f in gtk_viewport_size_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#20 0x00007ffff7ac0d4f in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#21 0x00007ffff79fece1 in gtk_scrolled_window_allocate_child () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#22 0x00007ffff79ff1a7 in gtk_scrolled_window_size_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#23 0x00007ffff7ac0d4f in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#24 0x00007ffff78d2401 in gtk_box_layout_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#25 0x00007ffff7ac0bfe in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#26 0x00007ffff78d2401 in gtk_box_layout_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#27 0x00007ffff7ac0bfe in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#28 0x00007ffff78b2477 in gtk_bin_layout_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#29 0x00007ffff7ac0bfe in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#30 0x00007ffff7ac0d4f in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#31 0x00007ffff78d2401 in gtk_box_layout_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#32 0x00007ffff7ac0bfe in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#33 0x00007ffff79c6d8b in gtk_overlay_layout_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#34 0x00007ffff7ac0bfe in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#35 0x00007ffff7a2810b in gtk_stack_size_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#36 0x00007ffff7ac0d4f in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#37 0x00007ffff7ad0378 in gtk_window_size_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#38 0x00007ffff7ac0d4f in gtk_widget_allocate () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#39 0x00007ffff7acbcef in gtk_window_native_layout () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#40 0x00007ffff79f556b in surface_layout_cb () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#41 0x00007ffff7bb1b9a in _gdk_marshal_VOID__INT_INTv () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#42 0x00007ffff729b849 in _g_closure_invoke_va () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libgobject-2.0.so.0
#43 0x00007ffff72b4153 in g_signal_emit_valist () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libgobject-2.0.so.0
#44 0x00007ffff72b441f in g_signal_emit () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libgobject-2.0.so.0
#45 0x00007ffff729b61f in g_closure_invoke () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libgobject-2.0.so.0
#46 0x00007ffff72ad637 in signal_emit_unlocked_R () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libgobject-2.0.so.0
#47 0x00007ffff72b3e71 in g_signal_emit_valist () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libgobject-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#48 0x00007ffff72b441f in g_signal_emit () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libgobject-2.0.so.0
#49 0x00007ffff7bcbaa3 in gdk_frame_clock_paint_idle () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#50 0x00007ffff7bcbc47 in gdk_frame_clock_flush_idle () from /nix/store/pz1j360zwynsadb4jldxq8wqnxnkipi4-gtk4-4.7.1/lib/libgtk-4.so.1
#51 0x00007ffff71a2874 in g_timeout_dispatch () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libglib-2.0.so.0
#52 0x00007ffff71a1d04 in g_main_context_dispatch () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libglib-2.0.so.0
#53 0x00007ffff71a20a8 in g_main_context_iterate.constprop () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libglib-2.0.so.0
#54 0x00007ffff71a215f in g_main_context_iteration () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libglib-2.0.so.0
#55 0x00007ffff73c671d in g_application_run () from /nix/store/38ychklifhkvfjzgqr1i97916cmiwdhj-glib-2.72.3/lib/libgio-2.0.so.0
#56 0x0000000001857fee in _cgo_60a35a354f58_Cfunc_g_application_run (v=0xc00058fae0) at /tmp/go-build/cgo-gcc-prolog:453
#57 0x00000000005d6f84 in runtime.asmcgocall () at /nix/store/va8n177r49nyk49y3s5fm9m1bgmjxcsm-go-1.18/share/go/src/runtime/asm_amd64.s:821
#58 0x000000c0004cdba0 in ?? ()
#59 0x00007fffaaffcb40 in ?? ()
#60 0x00000000005b1173 in runtime.newproc.func1 () at /nix/store/va8n177r49nyk49y3s5fm9m1bgmjxcsm-go-1.18/share/go/src/runtime/proc.go:4062
#61 0x00000000005d5109 in runtime.systemstack () at /nix/store/va8n177r49nyk49y3s5fm9m1bgmjxcsm-go-1.18/share/go/src/runtime/asm_amd64.s:469
#62 0x00007fffaaffd640 in ?? ()
#63 0x0000000000800000 in ?? ()
#64 0x0000000000000000 in ?? ()
```

**Comment by diamondburned** [comment]
At one point during GTK updates, issue https://github.com/diamondburned/gtkcord4/issues/40 would happen instead of this. Closing this issue since it's not applicable anymore.
