### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by Laar3** [diamondburned/gtkcord4#54]
upon downloading the aarch64 linux version on my pinephone running arch linux arm i get this error
```
2022/08/11 23:43:53 failed to read user.css: open /home/spagett/.config/gtkcord4/user.css: no such file or directory
2022/08/11 23:43:53 note: account not found from driver: key not found
2022/08/11 23:43:53 Warning: Gtk: GtkGizmo 0xffff5c1253f0 (progress) reported min width -2, but sizes must be >= 0
**
Gsk:ERROR:../gtk/gsk/gl/gskglcommandqueue.c:1276:gsk_gl_command_queue_create_render_target: assertion failed (glCheckFramebufferStatus (GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE): (0x00008cd6 == 0x00008cd5)
Bail out! Gsk:ERROR:../gtk/gsk/gl/gskglcommandqueue.c:1276:gsk_gl_command_queue_create_render_target: assertion failed (glCheckFramebufferStatus (GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE): (0x00008cd6 == 0x00008cd5)
SIGABRT: abort
PC=0xffff95cc2790 m=3 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x1797ae8, 0x400054bac8)
	runtime/cgocall.go:157 +0x54 fp=0x400054ba90 sp=0x400054ba50 pc=0x5787a4
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x42c7f290, 0x1, 0xffff5c002790)
	_cgo_gotypes.go:5619 +0x3c fp=0x400054bac0 sp=0x400054ba90 pc=0x6c209c
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x40002c2070?, 0xa?, 0xffff5c002790?)
	github.com/diamondburned/gotk4/pkg@v0.0.0-20220417091308-856167c02355/gio/v2/gapplication.go:1619 +0x78 fp=0x400054bb10 sp=0x400054bac0 pc=0x705938
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0x40005816f8, {0x40001101f0?, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.0.0-20220417091308-856167c02355/gio/v2/gapplication.go:1619 +0x184 fp=0x400054bbd0 sp=0x400054bb10 pc=0x705854
github.com/diamondburned/gotkit/app.(*Application).Run(0x40001dc200, {0x40001101f0, 0x1, 0x1})
	github.com/diamondburned/gotkit@v0.0.0-20220622054943-8c1f46952fc5/app/app.go:235 +0x164 fp=0x400054bc30 sp=0x400054bbd0 pc=0xd229d4
github.com/diamondburned/gotkit/app.(*Application).RunMain(0x1e53f60?)
	github.com/diamondburned/gotkit@v0.0.0-20220622054943-8c1f46952fc5/app/app.go:240 +0x44 fp=0x400054bc60 sp=0x400054bc30 pc=0xd22b44
main.main()
	github.com/diamondburned/gtkcord4/main.go:47 +0x594 fp=0x400054bf70 sp=0x400054bc60 pc=0x17295f4
runtime.main()
	runtime/proc.go:250 +0x258 fp=0x400054bfd0 sp=0x400054bf70 pc=0x5aac08
runtime.goexit()
	runtime/asm_arm64.s:1259 +0x4 fp=0x400054bfd0 sp=0x400054bfd0 pc=0x5d8e74

goroutine 22 [chan receive]:
github.com/diamondburned/gotkit/gtkutil/aggressivegc.init.0.func1()
	github.com/diamondburned/gotkit@v0.0.0-20220622054943-8c1f46952fc5/gtkutil/aggressivegc/aggressivegc.go:17 +0x58
created by github.com/diamondburned/gotkit/gtkutil/aggressivegc.init.0
	github.com/diamondburned/gotkit@v0.0.0-20220622054943-8c1f46952fc5/gtkutil/aggressivegc/aggressivegc.go:16 +0x28

goroutine 38 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:151 +0x34
os/signal.loop()
	os/signal/signal_unix.go:23 +0x20
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x30

goroutine 39 [select]:
os/signal.NotifyContext.func1()
	os/signal/signal.go:288 +0x6c
created by os/signal.NotifyContext
	os/signal/signal.go:287 +0x184

goroutine 40 [chan receive]:
github.com/diamondburned/gotkit/app.(*Application).Run.func1()
	github.com/diamondburned/gotkit@v0.0.0-20220622054943-8c1f46952fc5/app/app.go:231 +0x3c
created by github.com/diamondburned/gotkit/app.(*Application).Run
	github.com/diamondburned/gotkit@v0.0.0-20220622054943-8c1f46952fc5/app/app.go:230 +0x148

goroutine 26 [chan receive]:
github.com/godbus/dbus/v5.newConn.func1()
	github.com/godbus/dbus/v5@v5.0.6/conn.go:288 +0x3c
created by github.com/godbus/dbus/v5.newConn
	github.com/godbus/dbus/v5@v5.0.6/conn.go:287 +0x19c

goroutine 27 [IO wait]:
internal/poll.runtime_pollWait(0xffff69ea8998, 0x72)
	runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x40001dc280?, 0x40001cc920?, 0x0)
	internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).ReadMsg(0x40001dc280, {0x40001cc920, 0x10, 0x10}, {0x40000e7320, 0x1000, 0x1000}, 0x4?)
	internal/poll/fd_unix.go:304 +0x218
net.(*netFD).readMsg(0x40001dc280, {0x40001cc920?, 0x400023c500?, 0x40002422f8?}, {0x40000e7320?, 0x40002365a0?, 0x40001cc90c?}, 0x40001cc824?)
	net/fd_posix.go:78 +0x30
net.(*UnixConn).readMsg(0x40001f5fb8, {0x40001cc920?, 0x357a758?, 0x1?}, {0x40000e7320?, 0x400023c500?, 0x1e4abc8?})
	net/unixsock_posix.go:115 +0x38
net.(*UnixConn).ReadMsgUnix(0x40001f5fb8, {0x40001cc920?, 0x40?, 0x3714d50?}, {0x40000e7320?, 0x5813e0?, 0x4000215d28?})
	net/unixsock.go:143 +0x34
github.com/godbus/dbus/v5.(*oobReader).Read(0x40000e7300, {0x40001cc920?, 0x4000215da8?, 0x166f0c4?})
	github.com/godbus/dbus/v5@v5.0.6/transport_unix.go:21 +0x40
io.ReadAtLeast({0x1e4b148, 0x40000e7300}, {0x40001cc920, 0x10, 0x10}, 0x10)
	io/io.go:331 +0xac
io.ReadFull(...)
	io/io.go:350
github.com/godbus/dbus/v5.(*unixTransport).ReadMessage(0x40005817a0)
	github.com/godbus/dbus/v5@v5.0.6/transport_unix.go:91 +0x110
github.com/godbus/dbus/v5.(*Conn).inWorker(0x4000390690)
	github.com/godbus/dbus/v5@v5.0.6/conn.go:389 +0x44
created by github.com/godbus/dbus/v5.(*Conn).Auth
	github.com/godbus/dbus/v5@v5.0.6/auth.go:118 +0x748

r0      0x0
r1      0x15cdb5
r2      0x6
r3      0xffff6aeedf60
r4      0xffff96fffa48
r5      0xffff5c1be720
r6      0xa0aaf938b5195e35
r7      0x6b74672f2e2e3a52
r8      0x83
r9      0x3664633830303030
r10     0x30307830203d3d20
r11     0x29356463383030
r12     0x2820737574617453
r13     0x454d4152465f4c47
r14     0x2029524546465542
r15     0x52465f4c47203d3d
r16     0x0
r17     0x0
r18     0x4
r19     0x15cdb5
r20     0xffff6aeedf60
r21     0x6
r22     0xffff95fdb020
r23     0xffff6aeebdb8
r24     0xffff96c6b620
r25     0x2600
r26     0x2600
r27     0xffff5c1a48d0
r28     0xffff6aeec150
r29     0xffff6aeebb10
lr      0xffff95cc277c
sp      0xffff6aeebb10
pc      0xffff95cc2790
fault   0x0
```

**Comment by diamondburned** [comment]
That is very weird. You might have to run it in `gdb` and call `bt` to get the full C stack trace.

**Comment by Laar3** [comment]
Sorry for the wait but i cant reproduce the error with gdb, it makes no sense to me why this is. if i run `gdb ./gtkcord4` and enter `start` and then `continue` it works perfectly fine 100% of the time, when run without gdb it still crashes a majority of the time.
Ive edited my launcher entry to run it through gdb and its working fine with that so if no one else has this issue maybe it should be closed? im really not sure what is happening.

**Comment by diamondburned** [comment]
> when run without gdb it still crashes a majority of the time

Were you running this in the same terminal environment as `gdb`?

**Comment by Laar3** [comment]
Yep, right after running it through gdb, same zsh session, everything
